### ISSUE TITLE
Booktabs called twice in preamble

### ISSUE THREAD

**Issue by NilsEnevoldsen** [derekwolfson/tex3pt#1]
`\usepackage{booktabs}` appears twice in the preamble.

**Comment by derekwolfson** [comment]
Fixed - Thanks for suggestion.  I'll close when it is up on SSC.

**Comment by NilsEnevoldsen** [comment]
FYI, if you put the issue number in the comments of your commit ("Fixes #1"), then GitHub will automatically link that commit from the issue. I've commented on your commit to achieve that in this case.

**Comment by derekwolfson** [comment]
Thanks Nils.  I’m pretty new to Github, so I appreciate the tip.
