### ISSUE TITLE
Star note is not formatted properly

### ISSUE THREAD

**Issue by NilsEnevoldsen** [derekwolfson/tex3pt#12]
1. _p_ is a variable, and should therefore be italic.
2. There should be appropriate space around binary operators.
3. Leading zero was dropped with 2cf36c5. Probability cannot exceed 1, so I support this.

The first two can be easily solved by extending math mode around the _p_.

The third was recently fixed, but I thought I'd mention it explicitly.

**Comment by NilsEnevoldsen** [comment]
I just noticed that these should also have nonbreaking spaces, e.g. `**~$p<.05$`.

**Comment by derekwolfson** [comment]
Very good call. 

-D

Typed with two thumbs.

**Comment by NilsEnevoldsen** [comment]
More fixes in 90bd594 and 843b40a.
