### ISSUE TITLE
OS X support for compile option 

### ISSUE THREAD

**Issue by NilsEnevoldsen** [derekwolfson/tex3pt#15]
This can be done with syntax similar to the following:
`shell PATH=\$PATH:/usr/local/bin:/usr/texbin && latexmk etc…`

**Comment by derekwolfson** [comment]
This is noted here too: http://www.statalist.org/forums/forum/general-stata-discussion/general/2008-new-ado-for-making-latex-and-stata-play-nicely

I'll admit, I wanted to integrate this, but I don't have a mac machine that I can test this on.  Nils do you? Or perhaps we can enlist a mac user?

**Comment by NilsEnevoldsen** [comment]
Yes, I use OS X. I'll put it on my list.

**Comment by NilsEnevoldsen** [comment]
This might work on other *nix systems, but it is only enabled for OS X.

**Comment by NilsEnevoldsen** [comment]
Drat. Forgot to update the help file.

edit: Done.
