### ISSUE TITLE
Default font should be default font, not Libertine

### ISSUE THREAD

**Issue by NilsEnevoldsen** [derekwolfson/tex3pt#2]
Unless I am overlooking something, there is no downside to having the following:

```
%TEXTFONT
 %DEFAULT
%MATHFONT
 %DEFAULT
```

**Comment by derekwolfson** [comment]
Agreed. Will close when updated on SSC.

**Comment by NilsEnevoldsen** [comment]
To be quite honest, I expected some pushback on this. :-)

Remember to update the help file as well.

**Comment by derekwolfson** [comment]
Nah it's ok!  I don't want my favorite font to go the way of Helvectica! 

Computer Modern is more erudite anyways.

-D

Typed with two thumbs.

**Comment by derekwolfson** [comment]
Still not on SSC, but fixed in the code here.

**Comment by derekwolfson** [comment]
Not on SSC yet.
