### ISSUE TITLE
Cluster variables with underscores break LaTeX

### ISSUE THREAD

**Issue by NilsEnevoldsen** [derekwolfson/tex3pt#26]
Cluster variables are passed through to LaTeX. If they contain an underscore, they will break table generation. `_` should be replaced with `\textunderscore` (with an added space at the end) or similar.

**Comment by NilsEnevoldsen** [comment]
We might need to look for underscores in other places as well. I haven't battle-tested this.

**Comment by NilsEnevoldsen** [comment]
Notably, `estout` help says

> For example, specify `substitute(_ \_)` to replace the underscore character (as in `_cons` or `F_p`) with it's LaTeX equivalent `\_`.

This doesn't help solve this issue, but it's related.

**Comment by derekwolfson** [comment]
Should be pretty easy to implement – just need to do a subinstr command on the cluster_var local.  I do some character substitution at some point for other protected characters like $ and & in other places.  Just putting this as a note so I don’t forget!
