### ISSUE TITLE
LaTeX commands in notes aren't possible

### ISSUE THREAD

**Issue by NilsEnevoldsen** [derekwolfson/tex3pt#33]
This code is giving me problems:

``` stata
**SUBSTITUTE SPECIAL LATEX CHARACTERS** NOT WORKING FIX THIS LATER
foreach string in title note{
    local `string': subinstr local `string' "\" "\text{\}", all
    local `string': subinstr local `string' "\$" "\\\$", all
    foreach character in "%" "&" "{" "}" "_" "#"{
        local `string': subinstr local `string' "`character'" "\\`character'", all
    }
}
```

This means I can't use LaTeX math or references in tables notes. I have stripped this section out of my tex3pt, since I can always escape table notes by hand. This change breaks backward compatibility. I think the Stata substitutions are quite limited – just `\$`, `\``, and `\\`. After that, LaTeX can have a field day.

Unfortunately, I come bearing only problems, not their solutions.

**Comment by derekwolfson** [comment]
we should truncate the substitution command.  I agree 100% with the fix you made. I did this without thinking. 

-D

Typed with two thumbs.

**Comment by NilsEnevoldsen** [comment]
_Truncate_ means _shorten_. Do you mean we should _remove_ the substitution command entirely, or do I misunderstand?

**Comment by derekwolfson** [comment]
remove.

-D

Typed with two thumbs.
