### ISSUE TITLE
Submit 2.0.5 to SSC

### ISSUE THREAD

**Issue by NilsEnevoldsen** [derekwolfson/tex3pt#35]

**Comment by derekwolfson** [comment]
Nils.  Is this the current state of repo?  I want to make a release before sending just so we can have some sense of a timeline.  

Sorry for falling off the map... first year of grad school is consuming my time.  I am so grateful that you are continuing to develop!

**Comment by NilsEnevoldsen** [comment]
I haven't touched the repo, sorry. You created 2.0.5 last year, but never sent it off to SSC. :smile:

**Comment by derekwolfson** [comment]
Haha. Ok thanks for keeping me honest!!

-D

Typed with two thumbs.

**Comment by derekwolfson** [comment]
Changed version to 2.1.0 -- sent to SSC.
